import type {
  CompetitorResponse,
  ExecutiveRailSignal,
  Recommendation,
  ScenarioKpi,
  ScenarioPreset,
  TimelineSignal,
} from "@/components/command-center/scenario/types";

export const SCENARIO_KPIS: ScenarioKpi[] = [
  {
    id: "k1",
    label: "Scenario Confidence",
    value: "91.6",
    deltaPct: 3.5,
    confidence: 92,
    momentum: "accelerating",
    commentary: "Model confidence improved after new demand and influence telemetry.",
    sparkline: [
      { x: "1", y: 56 },
      { x: "2", y: 62 },
      { x: "3", y: 69 },
      { x: "4", y: 75 },
      { x: "5", y: 82 },
      { x: "6", y: 89 },
    ],
  },
  {
    id: "k2",
    label: "Prestige Stability",
    value: "84.9",
    deltaPct: -1.2,
    confidence: 85,
    momentum: "cooling",
    commentary: "Prestige stability softened under competitor narrative pressure.",
    sparkline: [
      { x: "1", y: 74 },
      { x: "2", y: 75 },
      { x: "3", y: 74 },
      { x: "4", y: 73 },
      { x: "5", y: 71 },
      { x: "6", y: 69 },
    ],
  },
  {
    id: "k3",
    label: "Revenue Projection",
    value: "$12.8M",
    deltaPct: 4.8,
    confidence: 90,
    momentum: "accelerating",
    commentary: "Projected revenue path strengthens with current strategy mix.",
    sparkline: [
      { x: "1", y: 44 },
      { x: "2", y: 50 },
      { x: "3", y: 57 },
      { x: "4", y: 64 },
      { x: "5", y: 72 },
      { x: "6", y: 80 },
    ],
  },
  {
    id: "k4",
    label: "Influence Momentum",
    value: "+17.2%",
    deltaPct: 5.3,
    confidence: 88,
    momentum: "accelerating",
    commentary: "Influence deployment scenarios show stronger trust transfer carryover.",
    sparkline: [
      { x: "1", y: 41 },
      { x: "2", y: 47 },
      { x: "3", y: 54 },
      { x: "4", y: 61 },
      { x: "5", y: 69 },
      { x: "6", y: 77 },
    ],
  },
  {
    id: "k5",
    label: "Market Risk Index",
    value: "28.4",
    deltaPct: -2.1,
    confidence: 86,
    momentum: "stable",
    commentary: "Risk index improved but remains sensitive to competitor escalation.",
    sparkline: [
      { x: "1", y: 49 },
      { x: "2", y: 47 },
      { x: "3", y: 44 },
      { x: "4", y: 41 },
      { x: "5", y: 38 },
      { x: "6", y: 35 },
    ],
  },
  {
    id: "k6",
    label: "Strategic Yield",
    value: "7.4x",
    deltaPct: 3.1,
    confidence: 89,
    momentum: "stable",
    commentary: "Strategic decisions from simulation outputs are yielding stronger outcomes.",
    sparkline: [
      { x: "1", y: 46 },
      { x: "2", y: 51 },
      { x: "3", y: 57 },
      { x: "4", y: 63 },
      { x: "5", y: 68 },
      { x: "6", y: 73 },
    ],
  },
];

export const PRESETS: ScenarioPreset[] = [
  {
    id: "balanced",
    name: "Balanced Institutional",
    description: "Moderate growth with controlled prestige and risk posture.",
    aggression: 50,
    riskTolerance: 45,
    capitalAllocation: 52,
    influenceBudget: 48,
    founderContent: 55,
    luxuryPositioning: 60,
    influencerDeployment: 50,
    prActivation: 45,
    investorMessaging: 58,
    geographicExpansion: 40,
    pricingChange: 42,
    narrativeFraming: 60,
  },
  {
    id: "offensive",
    name: "Offensive Dominance",
    description: "High aggression strategy for rapid market share and narrative control.",
    aggression: 82,
    riskTolerance: 72,
    capitalAllocation: 78,
    influenceBudget: 74,
    founderContent: 80,
    luxuryPositioning: 76,
    influencerDeployment: 84,
    prActivation: 72,
    investorMessaging: 78,
    geographicExpansion: 70,
    pricingChange: 68,
    narrativeFraming: 82,
  },
  {
    id: "defensive",
    name: "Defensive Prestige",
    description: "Risk-first strategy to preserve trust and prestige under volatility.",
    aggression: 32,
    riskTolerance: 28,
    capitalAllocation: 40,
    influenceBudget: 36,
    founderContent: 52,
    luxuryPositioning: 68,
    influencerDeployment: 34,
    prActivation: 46,
    investorMessaging: 62,
    geographicExpansion: 26,
    pricingChange: 30,
    narrativeFraming: 70,
  },
];

export const AI_RECOMMENDATIONS: Recommendation[] = [
  { id: "a1", action: "Increase founder narrative frequency", confidence: 92, impact: "+11 trust lift", priority: "critical" },
  { id: "a2", action: "Reduce prestige dilution", confidence: 90, impact: "-8 instability", priority: "critical" },
  { id: "a3", action: "Shift creator cluster deployment", confidence: 87, impact: "+9 influence momentum", priority: "high" },
  { id: "a4", action: "Increase HNWI targeting", confidence: 89, impact: "+12 conversion probability", priority: "critical" },
  { id: "a5", action: "Increase exclusivity framing", confidence: 84, impact: "+7 prestige stability", priority: "high" },
  { id: "a6", action: "Reduce pricing volatility", confidence: 86, impact: "-6 risk index", priority: "high" },
  { id: "a7", action: "Expand trust reinforcement", confidence: 88, impact: "+10 sentiment resilience", priority: "high" },
  { id: "a8", action: "Delay campaign launch", confidence: 79, impact: "-5 escalation risk", priority: "medium" },
  { id: "a9", action: "Accelerate investor positioning", confidence: 91, impact: "+13 investor confidence", priority: "critical" },
  { id: "a10", action: "Optimize luxury segmentation", confidence: 85, impact: "+8 market penetration", priority: "high" },
];

export const COMPETITOR_RESPONSES: CompetitorResponse[] = [
  {
    id: "c1",
    vector: "Counter-positioning campaign",
    probability: 78,
    severity: "high",
    implication: "Expect rapid narrative reframing in premium districts.",
  },
  {
    id: "c2",
    vector: "Pricing response",
    probability: 64,
    severity: "medium",
    implication: "Short-term discount signaling likely in two segments.",
  },
  {
    id: "c3",
    vector: "Narrative attack",
    probability: 57,
    severity: "medium",
    implication: "Credibility challenge on exclusivity claims possible.",
  },
  {
    id: "c4",
    vector: "Influencer redeployment",
    probability: 72,
    severity: "high",
    implication: "Competing creator clusters may shift toward DIFC and Palm.",
  },
  {
    id: "c5",
    vector: "Audience migration push",
    probability: 61,
    severity: "medium",
    implication: "Potential HNWI attention diversion in 30-day horizon.",
  },
  {
    id: "c6",
    vector: "Market saturation pressure",
    probability: 48,
    severity: "low",
    implication: "Category noise increase likely if campaign overlap continues.",
  },
];

export const TIMELINE_SIGNALS: TimelineSignal[] = [
  { id: "t1", horizon: "7d", label: "Immediate narrative shift", note: "Founder content increase predicts +6 trust momentum.", severity: "medium" },
  { id: "t2", horizon: "30d", label: "Luxury demand migration", note: "Palm and DIFC projected to absorb premium intent uplift.", severity: "high" },
  { id: "t3", horizon: "90d", label: "Competitor adaptation", note: "Counter-positioning probability exceeds 70% in aggressive scenarios.", severity: "high" },
  { id: "t4", horizon: "180d", label: "Prestige trajectory divergence", note: "Exclusivity framing quality becomes key stability driver.", severity: "medium" },
  { id: "t5", horizon: "long", label: "Authority evolution", note: "Consistent trust reinforcement yields durable market authority.", severity: "low" },
];

export const EXEC_RAIL: ExecutiveRailSignal[] = [
  { id: "e1", type: "risk", title: "Strategic risk", body: "Aggressive pricing variable increased downside exposure by 4 points.", timestamp: "4m ago" },
  { id: "e2", type: "instability", title: "Forecast instability", body: "Prestige trajectory confidence widened under current controls.", timestamp: "9m ago" },
  { id: "e3", type: "volatility", title: "Prestige volatility", body: "Narrative framing mismatch detected in one audience cohort.", timestamp: "15m ago" },
  { id: "e4", type: "confidence", title: "Confidence drop", body: "Investor sentiment confidence dipped below 82 in 90-day model.", timestamp: "21m ago" },
  { id: "e5", type: "escalation", title: "Competitive escalation", body: "Influencer redeployment response probability crossed 70%.", timestamp: "29m ago" },
  { id: "e6", type: "narrative", title: "Narrative instability", body: "Competing themes creating trust fragmentation signal.", timestamp: "33m ago" },
  { id: "e7", type: "saturation", title: "Market saturation warning", body: "Campaign overlap may reduce luxury attention quality.", timestamp: "41m ago" },
];
