import type {
  AudiencePoint,
  CreatorRow,
  CulturalPoint,
  DistrictHeat,
  ExecutiveRailSignal,
  InfluenceKpi,
  Recommendation,
  TrustTransferPoint,
} from "@/components/command-center/influence/types";

export const INFLUENCE_KPIS: InfluenceKpi[] = [
  {
    id: "k1",
    label: "Influence Yield",
    value: "8.1x",
    deltaPct: 5.2,
    confidence: 92,
    momentum: "accelerating",
    commentary: "Yield rose after pairing high-trust creators with founder crossover assets.",
    sparkline: [
      { x: "1", y: 44 },
      { x: "2", y: 50 },
      { x: "3", y: 57 },
      { x: "4", y: 63 },
      { x: "5", y: 70 },
      { x: "6", y: 77 },
    ],
  },
  {
    id: "k2",
    label: "Prestige Density",
    value: "91.4",
    deltaPct: 2.7,
    confidence: 88,
    momentum: "stable",
    commentary: "Prestige concentration remains above luxury benchmark threshold.",
    sparkline: [
      { x: "1", y: 62 },
      { x: "2", y: 67 },
      { x: "3", y: 72 },
      { x: "4", y: 77 },
      { x: "5", y: 83 },
      { x: "6", y: 88 },
    ],
  },
  {
    id: "k3",
    label: "Trust Transfer Score",
    value: "87.9",
    deltaPct: 3.8,
    confidence: 90,
    momentum: "accelerating",
    commentary: "Creator-to-brand trust transfer increased in HNWI audience slices.",
    sparkline: [
      { x: "1", y: 58 },
      { x: "2", y: 61 },
      { x: "3", y: 66 },
      { x: "4", y: 71 },
      { x: "5", y: 76 },
      { x: "6", y: 81 },
    ],
  },
  {
    id: "k4",
    label: "Audience Wealth Index",
    value: "84.6",
    deltaPct: 1.9,
    confidence: 85,
    momentum: "stable",
    commentary: "Audience mix shifted toward higher-net-worth clusters in Dubai and London.",
    sparkline: [
      { x: "1", y: 57 },
      { x: "2", y: 60 },
      { x: "3", y: 63 },
      { x: "4", y: 67 },
      { x: "5", y: 71 },
      { x: "6", y: 75 },
    ],
  },
  {
    id: "k5",
    label: "Narrative Velocity",
    value: "+16.8%",
    deltaPct: 4.4,
    confidence: 87,
    momentum: "accelerating",
    commentary: "High-clarity luxury narratives are compounding faster than generic content.",
    sparkline: [
      { x: "1", y: 49 },
      { x: "2", y: 54 },
      { x: "3", y: 60 },
      { x: "4", y: 66 },
      { x: "5", y: 73 },
      { x: "6", y: 79 },
    ],
  },
  {
    id: "k6",
    label: "Conversion Gravity",
    value: "73.2",
    deltaPct: 3.1,
    confidence: 86,
    momentum: "stable",
    commentary: "Conversion pull remains strongest in Elite Finance and Luxury Lifestyle clusters.",
    sparkline: [
      { x: "1", y: 46 },
      { x: "2", y: 50 },
      { x: "3", y: 56 },
      { x: "4", y: 61 },
      { x: "5", y: 67 },
      { x: "6", y: 72 },
    ],
  },
];

export const CREATORS: CreatorRow[] = [
  {
    id: "c1",
    creator: "Lena Voss",
    platform: "LinkedIn",
    prestigeScore: 94,
    audienceWealthDensity: 91,
    luxuryAlignment: 88,
    conversionGravity: 84,
    trustTransferPotential: 92,
    influenceYield: 8.7,
    narrativeCategory: "Institutional luxury governance",
    riskLevel: "low",
    cluster: "Elite Finance",
    aiPriority: 98,
  },
  {
    id: "c2",
    creator: "Omar Belhadi",
    platform: "Instagram",
    prestigeScore: 89,
    audienceWealthDensity: 83,
    luxuryAlignment: 94,
    conversionGravity: 79,
    trustTransferPotential: 86,
    influenceYield: 7.9,
    narrativeCategory: "Ultra-luxury lifestyle authority",
    riskLevel: "medium",
    cluster: "Luxury Lifestyle",
    aiPriority: 91,
  },
  {
    id: "c3",
    creator: "Sofia Marin",
    platform: "YouTube",
    prestigeScore: 86,
    audienceWealthDensity: 80,
    luxuryAlignment: 87,
    conversionGravity: 82,
    trustTransferPotential: 85,
    influenceYield: 7.4,
    narrativeCategory: "Founder interview deep dives",
    riskLevel: "low",
    cluster: "Cultural Authority",
    aiPriority: 88,
  },
  {
    id: "c4",
    creator: "Rami Haddad",
    platform: "Podcast",
    prestigeScore: 82,
    audienceWealthDensity: 86,
    luxuryAlignment: 79,
    conversionGravity: 76,
    trustTransferPotential: 81,
    influenceYield: 6.8,
    narrativeCategory: "Capital and migration intelligence",
    riskLevel: "medium",
    cluster: "HNWI Mobility",
    aiPriority: 84,
  },
  {
    id: "c5",
    creator: "Nina Artois",
    platform: "X",
    prestigeScore: 78,
    audienceWealthDensity: 74,
    luxuryAlignment: 81,
    conversionGravity: 71,
    trustTransferPotential: 75,
    influenceYield: 6.1,
    narrativeCategory: "Cultural pulse commentary",
    riskLevel: "high",
    cluster: "Cultural Authority",
    aiPriority: 73,
  },
  {
    id: "c6",
    creator: "Karim Dastan",
    platform: "Instagram",
    prestigeScore: 90,
    audienceWealthDensity: 88,
    luxuryAlignment: 92,
    conversionGravity: 83,
    trustTransferPotential: 89,
    influenceYield: 8.2,
    narrativeCategory: "Luxury investment storytelling",
    riskLevel: "low",
    cluster: "Luxury Lifestyle",
    aiPriority: 95,
  },
];

export const AUDIENCE_INTEL: AudiencePoint[] = [
  { label: "W1", wealthConcentration: 61, hnwiOverlap: 57, luxuryBehavior: 59, culturalPositioning: 54, prestigeMigration: 51, attentionDensity: 56 },
  { label: "W2", wealthConcentration: 65, hnwiOverlap: 61, luxuryBehavior: 63, culturalPositioning: 58, prestigeMigration: 56, attentionDensity: 60 },
  { label: "W3", wealthConcentration: 69, hnwiOverlap: 66, luxuryBehavior: 68, culturalPositioning: 63, prestigeMigration: 60, attentionDensity: 65 },
  { label: "W4", wealthConcentration: 74, hnwiOverlap: 70, luxuryBehavior: 72, culturalPositioning: 68, prestigeMigration: 65, attentionDensity: 70 },
  { label: "W5", wealthConcentration: 79, hnwiOverlap: 75, luxuryBehavior: 77, culturalPositioning: 73, prestigeMigration: 70, attentionDensity: 75 },
  { label: "W6", wealthConcentration: 83, hnwiOverlap: 80, luxuryBehavior: 82, culturalPositioning: 77, prestigeMigration: 75, attentionDensity: 81 },
];

export const DISTRICT_HEATMAP: DistrictHeat[] = [
  { district: "Palm Jumeirah", luxuryAttention: 92, prestigeConcentration: 94, movement: 86, creatorTerritory: 88 },
  { district: "Downtown", luxuryAttention: 85, prestigeConcentration: 83, movement: 78, creatorTerritory: 81 },
  { district: "DIFC", luxuryAttention: 89, prestigeConcentration: 91, movement: 82, creatorTerritory: 86 },
  { district: "Dubai Marina", luxuryAttention: 73, prestigeConcentration: 69, movement: 71, creatorTerritory: 74 },
  { district: "Jumeirah Bay", luxuryAttention: 95, prestigeConcentration: 96, movement: 88, creatorTerritory: 91 },
  { district: "Business Bay", luxuryAttention: 68, prestigeConcentration: 64, movement: 66, creatorTerritory: 69 },
];

export const TRUST_TRANSFER: TrustTransferPoint[] = [
  { label: "W1", trustCompatibility: 62, brandSafety: 71, reputationAlignment: 64, sentimentStability: 59, authorityCrossover: 57, prestigeCompatibility: 63 },
  { label: "W2", trustCompatibility: 66, brandSafety: 74, reputationAlignment: 68, sentimentStability: 62, authorityCrossover: 61, prestigeCompatibility: 67 },
  { label: "W3", trustCompatibility: 70, brandSafety: 77, reputationAlignment: 72, sentimentStability: 66, authorityCrossover: 65, prestigeCompatibility: 71 },
  { label: "W4", trustCompatibility: 75, brandSafety: 80, reputationAlignment: 76, sentimentStability: 70, authorityCrossover: 70, prestigeCompatibility: 76 },
  { label: "W5", trustCompatibility: 80, brandSafety: 83, reputationAlignment: 81, sentimentStability: 74, authorityCrossover: 74, prestigeCompatibility: 81 },
  { label: "W6", trustCompatibility: 84, brandSafety: 86, reputationAlignment: 85, sentimentStability: 79, authorityCrossover: 79, prestigeCompatibility: 86 },
];

export const AI_RECOMMENDATIONS: Recommendation[] = [
  { id: "r1", action: "Deploy creator partnership", confidence: 92, impact: "+13 influence yield", priority: "critical" },
  { id: "r2", action: "Increase founder crossover", confidence: 89, impact: "+11 trust transfer", priority: "high" },
  { id: "r3", action: "Activate luxury narrative", confidence: 85, impact: "+8 prestige density", priority: "high" },
  { id: "r4", action: "Shift platform allocation", confidence: 83, impact: "+9 conversion gravity", priority: "medium" },
  { id: "r5", action: "Increase exclusivity framing", confidence: 86, impact: "+7 narrative velocity", priority: "high" },
  { id: "r6", action: "Expand HNWI penetration", confidence: 88, impact: "+10 wealth index", priority: "critical" },
  { id: "r7", action: "Reduce prestige dilution", confidence: 91, impact: "-6 reputation risk", priority: "critical" },
  { id: "r8", action: "Activate high-trust creator cluster", confidence: 90, impact: "+12 trust compatibility", priority: "critical" },
];

export const CULTURAL_MOMENTUM: CulturalPoint[] = [
  { label: "W1", narrativeShift: 55, trendAcceleration: 52, prestigeMigration: 50, audienceEvolution: 54, influenceSpikes: 49 },
  { label: "W2", narrativeShift: 59, trendAcceleration: 57, prestigeMigration: 55, audienceEvolution: 58, influenceSpikes: 54 },
  { label: "W3", narrativeShift: 64, trendAcceleration: 62, prestigeMigration: 60, audienceEvolution: 63, influenceSpikes: 59 },
  { label: "W4", narrativeShift: 69, trendAcceleration: 67, prestigeMigration: 65, audienceEvolution: 68, influenceSpikes: 64 },
  { label: "W5", narrativeShift: 75, trendAcceleration: 73, prestigeMigration: 71, audienceEvolution: 73, influenceSpikes: 70 },
  { label: "W6", narrativeShift: 81, trendAcceleration: 79, prestigeMigration: 76, audienceEvolution: 79, influenceSpikes: 76 },
];

export const EXECUTIVE_RAIL: ExecutiveRailSignal[] = [
  { id: "e1", type: "risk", title: "Influence risk", body: "One high-reach creator showing prestige dilution signals in 48h window.", timestamp: "5m ago" },
  { id: "e2", type: "anomaly", title: "Reputation anomaly", body: "Sentiment polarity divergence detected across two major creator clusters.", timestamp: "12m ago" },
  { id: "e3", type: "volatility", title: "Audience volatility", body: "HNWI overlap dipped 4 points in one district segment after competitor activation.", timestamp: "18m ago" },
  { id: "e4", type: "competitor", title: "Competitor creator activity", body: "Competitor increased spend in Luxury Lifestyle cluster by estimated 23%.", timestamp: "27m ago" },
  { id: "e5", type: "conflict", title: "Prestige conflict", body: "Narrative mismatch between exclusivity positioning and creator tone identified.", timestamp: "36m ago" },
  { id: "e6", type: "trend", title: "Trend acceleration", body: "Cultural momentum accelerating in DIFC audience cohort with positive trust carryover.", timestamp: "44m ago" },
];
