import type {
  AgentSpec,
  ExecutiveRailSignal,
  Recommendation,
  RecommendationMemory,
  SignalEvent,
} from "@/components/command-center/recommendation/types";

export const INITIAL_EVENTS: SignalEvent[] = [
  {
    id: "evt-01",
    source: "founder-authority",
    area: "founder-authority",
    magnitude: 78,
    direction: "up",
    velocity: 66,
    trust: 92,
    createdAt: "2m ago",
    note: "Founder long-form signal density increased in GCC premium segments.",
  },
  {
    id: "evt-02",
    source: "competitor-movement",
    area: "market-positioning",
    magnitude: 71,
    direction: "volatile",
    velocity: 74,
    trust: 81,
    createdAt: "4m ago",
    note: "Rival launched scarcity campaign targeting UHNW waterfront clusters.",
  },
  {
    id: "evt-03",
    source: "prestige-volatility",
    area: "prestige-stability",
    magnitude: 64,
    direction: "down",
    velocity: 58,
    trust: 88,
    createdAt: "7m ago",
    note: "Luxury sentiment variance widened after pricing narrative mismatch.",
  },
  {
    id: "evt-04",
    source: "lead-intelligence",
    area: "lead-intelligence",
    magnitude: 82,
    direction: "up",
    velocity: 69,
    trust: 90,
    createdAt: "10m ago",
    note: "HNWI referral lead purity up 12.4% in priority account cohorts.",
  },
  {
    id: "evt-05",
    source: "executive-engagement",
    area: "executive-risk",
    magnitude: 59,
    direction: "volatile",
    velocity: 52,
    trust: 86,
    createdAt: "14m ago",
    note: "Decision latency increased for high-ticket strategic approvals.",
  },
];

export const BASE_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec-001",
    title: "Reframe founder narrative around strategic certainty",
    summary: "Investor confidence is stable but exposed to pricing-led trust erosion over the next 30 days.",
    reasoning:
      "Founder authority and investor messaging divergence indicates a confidence gap. Synchronizing high-trust narratives with pricing justification suppresses volatility and improves premium conversion.",
    type: "founder-narrative",
    area: "founder-authority",
    suggestedActions: [
      "Deploy a 3-part founder intelligence brief tied to portfolio conviction.",
      "Pair each message with proof-based market evidence blocks.",
      "Route to executive accounts within 12 hours.",
    ],
    forecastOutcome: "+9.8% investor sentiment and -6.3 prestige volatility within one cycle.",
    urgency: "Next 18 hours",
    escalationState: "watch",
    supportingEvidence: [
      { source: "founder-authority", statement: "Authority velocity +14.2 in strategic segments.", weight: 0.34 },
      { source: "executive-engagement", statement: "Investor message coherence dropped 8.6.", weight: 0.27 },
      { source: "prestige-volatility", statement: "Prestige variance rose above tolerance threshold.", weight: 0.39 },
    ],
    score: {
      confidence: 89,
      strategicImpact: 91,
      revenueImpact: 82,
      prestigeImpact: 88,
      riskLevel: "high",
      timeSensitivity: 86,
      executionComplexity: 42,
      outcomeWindow: "7-30 days",
      priorityIndex: 90,
    },
    createdAt: "2m ago",
  },
  {
    id: "rec-002",
    title: "Trigger prestige shield protocol for pricing narrative",
    summary: "Prestige trajectory is vulnerable if discount signals remain visible in elite audience channels.",
    reasoning:
      "Luxury positioning elasticity has narrowed. Maintaining perceived scarcity while defending value articulation prevents audience migration and defensive competitor attacks.",
    type: "prestige-mitigation",
    area: "prestige-stability",
    suggestedActions: [
      "Replace discount language with invitation-only allocation framing.",
      "Push tiered access narrative to UHNW cohorts.",
      "Pause non-curated offer channels for 72 hours.",
    ],
    forecastOutcome: "Prestige risk down 11 points and migration pressure reduced by 18%.",
    urgency: "Immediate",
    escalationState: "urgent",
    supportingEvidence: [
      { source: "prestige-volatility", statement: "Volatility index crossed critical threshold 74.", weight: 0.45 },
      { source: "audience-migration", statement: "Audience drift toward competitor cluster C up 9.1%.", weight: 0.28 },
      { source: "competitor-movement", statement: "Rival scarcity narrative deployment detected.", weight: 0.27 },
    ],
    score: {
      confidence: 93,
      strategicImpact: 95,
      revenueImpact: 76,
      prestigeImpact: 97,
      riskLevel: "critical",
      timeSensitivity: 97,
      executionComplexity: 38,
      outcomeWindow: "24-72 hours",
      priorityIndex: 96,
    },
    createdAt: "4m ago",
  },
  {
    id: "rec-003",
    title: "Deploy influence strike in two high-leverage micro-networks",
    summary: "Influence resonance is strong but under-capitalized in the highest conversion narratives.",
    reasoning:
      "Cross-signal analysis identifies creator clusters with high trust transfer and low saturation. Concentrated deployment is projected to outpace broad campaigns on both conversion and prestige consistency.",
    type: "influence-deployment",
    area: "influence-system",
    suggestedActions: [
      "Activate 6 precision creators in finance-luxury overlap vertical.",
      "Sequence founder endorsement 6 hours after creator wave.",
      "Tie CTA to concierge conversion path.",
    ],
    forecastOutcome: "+14.6% lead quality and +8.2 revenue acceleration in 30 days.",
    urgency: "Next 36 hours",
    escalationState: "normal",
    supportingEvidence: [
      { source: "influence-network", statement: "Influence trust transfer coefficient at 0.82.", weight: 0.36 },
      { source: "conversion-change", statement: "Creator-assisted conversion efficiency +12.4%.", weight: 0.33 },
      { source: "lead-intelligence", statement: "HNWI lead confidence elevated in targeted cells.", weight: 0.31 },
    ],
    score: {
      confidence: 87,
      strategicImpact: 88,
      revenueImpact: 90,
      prestigeImpact: 79,
      riskLevel: "moderate",
      timeSensitivity: 73,
      executionComplexity: 55,
      outcomeWindow: "14-45 days",
      priorityIndex: 84,
    },
    createdAt: "6m ago",
  },
];

export const AGENT_SPECS: AgentSpec[] = [
  {
    name: "Market Intelligence Agent",
    inputs: ["Market intelligence feeds", "Sentiment shifts", "Conversion changes"],
    outputs: ["Opportunity spikes", "Trend inflections", "Positioning threats"],
    responsibilities: [
      "Detect high-value market dislocations.",
      "Quantify momentum and reversal probabilities.",
      "Provide forward market posture recommendations.",
    ],
    triggerConditions: ["Signal velocity > 70", "Sentiment inversion detected", "Competitor surge in priority segment"],
    coordinationFlows: ["Shares anomalies with Competitor Intelligence Agent", "Routes opportunity vectors to Executive Decision Agent"],
    escalationLogic: ["Escalate to urgent when adverse trend + high trust source + high revenue exposure"],
  },
  {
    name: "Founder Authority Agent",
    inputs: ["Founder authority metrics", "Executive engagement patterns"],
    outputs: ["Narrative actions", "Message coherence score"],
    responsibilities: [
      "Model authority trajectory and trust erosion risk.",
      "Recommend founder-led interventions.",
      "Align strategic narrative with market posture.",
    ],
    triggerConditions: ["Authority momentum drops for 2 cycles", "Engagement latency rises"],
    coordinationFlows: ["Coordinates with Narrative Strategy Agent", "Provides confidence gates to Executive Decision Agent"],
    escalationLogic: ["Escalate when confidence < 72 and prestige impact > 80"],
  },
  {
    name: "Influence Strategy Agent",
    inputs: ["Influence network signals", "Audience migration", "Creator performance"],
    outputs: ["Deployment recommendations", "Creator partnership opportunities"],
    responsibilities: [
      "Identify high-trust influence nodes.",
      "Optimize deployment timing and concentration.",
      "Reduce saturation and reputation risk.",
    ],
    triggerConditions: ["Audience migration spike", "Creator resonance > threshold"],
    coordinationFlows: ["Synchronizes with Revenue Optimization Agent", "Hands off risk exposures to Prestige Risk Agent"],
    escalationLogic: ["Escalate if migration + competitor capture exceed 15% delta"],
  },
  {
    name: "Prestige Risk Agent",
    inputs: ["Prestige volatility", "Sentiment shifts", "Pricing signals"],
    outputs: ["Risk mitigation plays", "Prestige resilience score"],
    responsibilities: [
      "Detect prestige instability and narrative dilution.",
      "Recommend protective brand posture changes.",
      "Trigger suppression of harmful recommendations.",
    ],
    triggerConditions: ["Prestige volatility > 70", "Negative sentiment acceleration"],
    coordinationFlows: ["Blocks contradictory high-risk actions", "Escalates red-state items to Executive Decision Agent"],
    escalationLogic: ["Immediate escalation for critical prestige events with high confidence"],
  },
  {
    name: "Revenue Optimization Agent",
    inputs: ["Lead intelligence events", "Conversion changes", "HNWI funnel metrics"],
    outputs: ["Revenue acceleration strategies", "Expected outcome windows"],
    responsibilities: [
      "Estimate revenue lift from strategic actions.",
      "Balance acceleration against prestige and risk constraints.",
      "Prioritize high-yield low-friction moves.",
    ],
    triggerConditions: ["Conversion deviation > 8%", "HNWI cohort expansion opportunities"],
    coordinationFlows: ["Feeds scoring engine with revenue impact", "Negotiates tradeoffs with Prestige Risk Agent"],
    escalationLogic: ["Escalate when revenue opportunity > 85 impact and time sensitivity > 80"],
  },
  {
    name: "Competitor Intelligence Agent",
    inputs: ["Competitor movements", "Market intelligence feeds", "Audience migration"],
    outputs: ["Competitive response actions", "Counter-positioning warnings"],
    responsibilities: [
      "Track adversarial campaign posture.",
      "Predict share capture attempts.",
      "Recommend timed response plays.",
    ],
    triggerConditions: ["Rival launch detected", "Share-of-voice shift > 10%"],
    coordinationFlows: ["Sends immediate threat models to Market Intelligence Agent", "Routes critical threats to Executive Decision Agent"],
    escalationLogic: ["Escalate to urgent for coordinated competitor pressure + prestige risk"],
  },
  {
    name: "Narrative Strategy Agent",
    inputs: ["Founder authority metrics", "Sentiment shifts", "Executive engagement"],
    outputs: ["Investor messaging shifts", "Strategic timing recommendations"],
    responsibilities: [
      "Refine strategic narrative sequence.",
      "Align message cadence with confidence windows.",
      "Prevent contradictory communication plays.",
    ],
    triggerConditions: ["Narrative coherence decline", "Investor confidence instability"],
    coordinationFlows: ["Aligns with Founder Authority Agent", "Submits timing envelopes to Priority Engine"],
    escalationLogic: ["Escalate when messaging misalignment threatens strategic outcomes"],
  },
  {
    name: "Executive Decision Agent",
    inputs: ["All agent outputs", "Priority engine", "Risk gates"],
    outputs: ["Final executive recommendations", "Escalation routing"],
    responsibilities: [
      "Resolve contradictions across agents.",
      "Apply suppression and dedupe policy.",
      "Route strategic actions by urgency and confidence.",
    ],
    triggerConditions: ["Any urgent recommendation", "Contradiction cluster detected"],
    coordinationFlows: ["Final node before recommendation feed", "Publishes to executive rail and mobile brief"],
    escalationLogic: ["Route critical conflicts to board escalation lane"],
  },
];

export const MEMORY_SEEDS: RecommendationMemory = {
  executiveInteractions: [
    "C-level reacted positively to founder conviction + proof sequence in last cycle.",
    "Risk-first alert cards are opened 2.3x more on mobile executive mode.",
  ],
  strategicHistory: [
    "Scarcity narrative sequence delivered strongest prestige stability in Q1.",
    "Broad influencer bursts caused prestige dilution in prior campaign.",
  ],
  recommendationOutcomes: [
    "Competitive response recommendation reduced share bleed by 7.8%.",
    "HNWI targeting optimization improved close rate by 11.1%.",
  ],
  organizationMemory: [
    "Institutional buyers prefer evidence-backed messaging in 2-step cadence.",
    "Executive team favors low-complexity actions in red-state volatility.",
  ],
  prestigeTrajectory: [
    "Prestige index stabilized after removing overt discount language.",
    "Narrative over-frequency historically increases volatility by 4-6 points.",
  ],
  narrativeEvolution: [
    "Authority narrative moved from aspirational to strategic certainty framing.",
    "Investor messaging now prioritizes downside protection plus upside optionality.",
  ],
};

export const EXECUTIVE_RAIL_BASE: ExecutiveRailSignal[] = [
  {
    id: "rail-1",
    title: "Urgent prestige threat",
    body: "Discount-adjacent language is leaking into high-value channels.",
    severity: "threat",
    confidenceDrift: -12,
  },
  {
    id: "rail-2",
    title: "Opportunity spike",
    body: "HNWI referral momentum entering high-conversion window.",
    severity: "opportunity",
    confidenceDrift: 9,
  },
  {
    id: "rail-3",
    title: "Confidence instability",
    body: "Investor confidence spread widened in 90-day cohort.",
    severity: "instability",
    confidenceDrift: -8,
  },
  {
    id: "rail-4",
    title: "Competitor escalation",
    body: "Rival initiated synchronized scarcity + creator push.",
    severity: "threat",
    confidenceDrift: -10,
  },
];
