import type { AlertItem, KpiMetric, Recommendation } from "@/components/command-center/home/types";

export const KPI_DATA: KpiMetric[] = [
  {
    id: "prestige-index",
    label: "Prestige Index",
    value: "96.4",
    deltaPct: 4.7,
    confidence: 93,
    commentary: "Brand authority compounding in DIFC and Palm clusters.",
    sparkline: [
      { x: "W1", y: 72 },
      { x: "W2", y: 75 },
      { x: "W3", y: 77 },
      { x: "W4", y: 81 },
      { x: "W5", y: 85 },
      { x: "W6", y: 88 },
      { x: "W7", y: 92 },
      { x: "W8", y: 96 },
    ],
  },
  {
    id: "revenue-pipeline",
    label: "Revenue Pipeline",
    value: "AED 1.42B",
    deltaPct: 7.3,
    confidence: 89,
    commentary: "High-intent inventory pressure increasing offer depth.",
    sparkline: [
      { x: "W1", y: 51 },
      { x: "W2", y: 58 },
      { x: "W3", y: 61 },
      { x: "W4", y: 63 },
      { x: "W5", y: 69 },
      { x: "W6", y: 72 },
      { x: "W7", y: 78 },
      { x: "W8", y: 84 },
    ],
  },
  {
    id: "lead-purity-ratio",
    label: "Lead Purity Ratio",
    value: "82.9%",
    deltaPct: 2.1,
    confidence: 91,
    commentary: "VIP filter quality stabilized after referral recalibration.",
    sparkline: [
      { x: "W1", y: 66 },
      { x: "W2", y: 68 },
      { x: "W3", y: 69 },
      { x: "W4", y: 70 },
      { x: "W5", y: 74 },
      { x: "W6", y: 77 },
      { x: "W7", y: 79 },
      { x: "W8", y: 83 },
    ],
  },
  {
    id: "founder-gravity-score",
    label: "Founder Gravity Score",
    value: "91.8",
    deltaPct: 6.8,
    confidence: 88,
    commentary: "Founder narratives are driving high-quality meeting conversion.",
    sparkline: [
      { x: "W1", y: 55 },
      { x: "W2", y: 57 },
      { x: "W3", y: 60 },
      { x: "W4", y: 65 },
      { x: "W5", y: 72 },
      { x: "W6", y: 78 },
      { x: "W7", y: 84 },
      { x: "W8", y: 92 },
    ],
  },
  {
    id: "qualified-attention",
    label: "Qualified Attention",
    value: "74.6",
    deltaPct: 3.4,
    confidence: 86,
    commentary: "Audience quality up despite tighter impression strategy.",
    sparkline: [
      { x: "W1", y: 47 },
      { x: "W2", y: 49 },
      { x: "W3", y: 52 },
      { x: "W4", y: 58 },
      { x: "W5", y: 63 },
      { x: "W6", y: 66 },
      { x: "W7", y: 71 },
      { x: "W8", y: 75 },
    ],
  },
  {
    id: "influence-yield-score",
    label: "Influence Yield Score",
    value: "89.2",
    deltaPct: 5.9,
    confidence: 92,
    commentary: "Influencer trust transfer yielding stronger downstream offers.",
    sparkline: [
      { x: "W1", y: 63 },
      { x: "W2", y: 65 },
      { x: "W3", y: 68 },
      { x: "W4", y: 70 },
      { x: "W5", y: 74 },
      { x: "W6", y: 78 },
      { x: "W7", y: 84 },
      { x: "W8", y: 89 },
    ],
  },
];

export const RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec-1",
    title: "Market opportunity detected",
    summary: "DIFC offshore buyer intent rose above strategic threshold after founder-led content release.",
    expectedUplift: "+11.2% pipeline quality",
    confidence: 91,
    riskLevel: "low",
    actionOwner: "Growth Director",
    timeline: "Execute in 24 hours",
    suggestedAction: "Shift 12% budget from broad prospecting into DIFC founder narrative cluster.",
  },
  {
    id: "rec-2",
    title: "Competitor velocity spike",
    summary: "Competitor campaign in Palm registered accelerated engagement among prestige segment C.",
    expectedUplift: "+7.9% conversion resilience",
    confidence: 84,
    riskLevel: "medium",
    actionOwner: "Market Intelligence Lead",
    timeline: "12-hour response window",
    suggestedAction: "Deploy counter-positioning with scarcity narrative and invite-only preview.",
  },
  {
    id: "rec-3",
    title: "High-intent buyer cluster forming",
    summary: "Cross-channel behavior indicates a consolidating HNWI segment around branded waterfront assets.",
    expectedUplift: "+15.4% qualified meetings",
    confidence: 88,
    riskLevel: "low",
    actionOwner: "Broker Operations",
    timeline: "48 hours",
    suggestedAction: "Assign top bilingual brokers and trigger concierge scheduling sequence.",
  },
  {
    id: "rec-4",
    title: "Founder authority surge",
    summary: "Authority index reached quarterly high, increasing trust velocity in strategic segments.",
    expectedUplift: "+9.1% lead purity",
    confidence: 90,
    riskLevel: "low",
    actionOwner: "Founder Office",
    timeline: "Next 72 hours",
    suggestedAction: "Publish boardroom-style insight brief and amplify through elite network channels.",
  },
  {
    id: "rec-5",
    title: "Inventory pressure rising",
    summary: "Premium inventory burn in targeted towers suggests upcoming pricing leverage.",
    expectedUplift: "+4.8% margin capture",
    confidence: 86,
    riskLevel: "medium",
    actionOwner: "Revenue Strategy",
    timeline: "Decision by EOD",
    suggestedAction: "Apply selective price lift to top decile demand cohorts only.",
  },
];

export const ALERTS: AlertItem[] = [
  {
    id: "a-1",
    type: "risk",
    title: "Risk alert",
    body: "Short-term liquidity concern detected in one referral sub-segment.",
    severity: "P1",
    timestamp: "5m ago",
  },
  {
    id: "a-2",
    type: "sentiment",
    title: "Sentiment volatility",
    body: "Brand sentiment in Downtown cluster dropped 4.2 points after competitor press push.",
    severity: "P2",
    timestamp: "17m ago",
  },
  {
    id: "a-3",
    type: "lead",
    title: "Lead quality shift",
    body: "Lead purity ratio down in external affiliate source by 8.1%.",
    severity: "P2",
    timestamp: "26m ago",
  },
  {
    id: "a-4",
    type: "competitor",
    title: "Competitor activity",
    body: "New launch inventory push detected in Palm from competitor cluster B.",
    severity: "P3",
    timestamp: "44m ago",
  },
  {
    id: "a-5",
    type: "market",
    title: "Market anomaly",
    body: "Unexpected high-intent spike from London buyer corridor.",
    severity: "P2",
    timestamp: "1h ago",
  },
];

export const REVENUE_ATTRIBUTION = [
  { month: "Jan", founder: 16, influencer: 24, paid: 28, referral: 18, direct: 14 },
  { month: "Feb", founder: 18, influencer: 27, paid: 26, referral: 16, direct: 13 },
  { month: "Mar", founder: 22, influencer: 29, paid: 24, referral: 14, direct: 11 },
  { month: "Apr", founder: 24, influencer: 28, paid: 23, referral: 15, direct: 10 },
  { month: "May", founder: 27, influencer: 26, paid: 22, referral: 14, direct: 11 },
  { month: "Jun", founder: 29, influencer: 25, paid: 21, referral: 14, direct: 11 },
];

export const MOMENTUM_DATA = [
  { day: "Mon", apex: 62, market: 55 },
  { day: "Tue", apex: 67, market: 56 },
  { day: "Wed", apex: 71, market: 58 },
  { day: "Thu", apex: 74, market: 60 },
  { day: "Fri", apex: 79, market: 61 },
  { day: "Sat", apex: 83, market: 63 },
  { day: "Sun", apex: 88, market: 64 },
];

export const FOUNDER_TIMELINE = [
  { week: "W1", authority: 54, conversion: 39 },
  { week: "W2", authority: 59, conversion: 43 },
  { week: "W3", authority: 66, conversion: 48 },
  { week: "W4", authority: 72, conversion: 55 },
  { week: "W5", authority: 81, conversion: 63 },
  { week: "W6", authority: 92, conversion: 71 },
];

export const INFLUENCE_MATRIX = [
  { name: "Tier-A Influencers", reach: 92, trust: 88, yield: 84 },
  { name: "Founder Channel", reach: 71, trust: 95, yield: 89 },
  { name: "Broker Network", reach: 66, trust: 82, yield: 78 },
  { name: "Private Referrals", reach: 48, trust: 93, yield: 91 },
];
