import type {
  ActionRecommendation,
  BuyerSegment,
  IntentPoint,
  LeadRow,
} from "@/components/command-center/lead/types";

export const SEGMENTS: BuyerSegment[] = [
  "Sovereign Capital",
  "Legacy Wealth",
  "Prestige Lifestyle",
  "Yield Strategists",
  "Relocation Elites",
];

export const LEAD_ROWS: LeadRow[] = [
  {
    id: "L-201",
    buyerName: "Hamad Al Qasimi",
    segment: "Sovereign Capital",
    intentScore: 94,
    prestigeScore: 97,
    brokerAssignment: "R. Volkov",
    probabilityToClose: 86,
    lastInteraction: "7m ago",
    aiPriorityLevel: "critical",
    conversationQuality: 92,
    responseLatencyMin: 4,
    emotionalSentiment: 81,
    conversionContribution: 19,
  },
  {
    id: "L-202",
    buyerName: "Sofia Von Heller",
    segment: "Legacy Wealth",
    intentScore: 89,
    prestigeScore: 95,
    brokerAssignment: "M. Laurent",
    probabilityToClose: 79,
    lastInteraction: "12m ago",
    aiPriorityLevel: "high",
    conversationQuality: 88,
    responseLatencyMin: 7,
    emotionalSentiment: 76,
    conversionContribution: 16,
  },
  {
    id: "L-203",
    buyerName: "Omar Rahman",
    segment: "Relocation Elites",
    intentScore: 83,
    prestigeScore: 87,
    brokerAssignment: "N. Delgado",
    probabilityToClose: 72,
    lastInteraction: "23m ago",
    aiPriorityLevel: "high",
    conversationQuality: 84,
    responseLatencyMin: 10,
    emotionalSentiment: 73,
    conversionContribution: 13,
  },
  {
    id: "L-204",
    buyerName: "Clara Bianchi",
    segment: "Prestige Lifestyle",
    intentScore: 77,
    prestigeScore: 90,
    brokerAssignment: "R. Volkov",
    probabilityToClose: 63,
    lastInteraction: "41m ago",
    aiPriorityLevel: "medium",
    conversationQuality: 75,
    responseLatencyMin: 14,
    emotionalSentiment: 69,
    conversionContribution: 11,
  },
  {
    id: "L-205",
    buyerName: "Arjun Malhotra",
    segment: "Yield Strategists",
    intentScore: 74,
    prestigeScore: 82,
    brokerAssignment: "K. Imani",
    probabilityToClose: 58,
    lastInteraction: "1h ago",
    aiPriorityLevel: "watch",
    conversationQuality: 71,
    responseLatencyMin: 16,
    emotionalSentiment: 65,
    conversionContribution: 9,
  },
  {
    id: "L-206",
    buyerName: "Noura Al Mazrouei",
    segment: "Sovereign Capital",
    intentScore: 91,
    prestigeScore: 96,
    brokerAssignment: "M. Laurent",
    probabilityToClose: 84,
    lastInteraction: "5m ago",
    aiPriorityLevel: "critical",
    conversationQuality: 90,
    responseLatencyMin: 5,
    emotionalSentiment: 80,
    conversionContribution: 18,
  },
];

export const INTENT_TREND: IntentPoint[] = [
  { label: "W1", intentTrend: 64, attentionDepth: 58, conversionReadiness: 51, trustAlignment: 56, urgencyMomentum: 49 },
  { label: "W2", intentTrend: 68, attentionDepth: 62, conversionReadiness: 56, trustAlignment: 60, urgencyMomentum: 54 },
  { label: "W3", intentTrend: 72, attentionDepth: 66, conversionReadiness: 60, trustAlignment: 64, urgencyMomentum: 59 },
  { label: "W4", intentTrend: 76, attentionDepth: 70, conversionReadiness: 65, trustAlignment: 68, urgencyMomentum: 63 },
  { label: "W5", intentTrend: 81, attentionDepth: 74, conversionReadiness: 70, trustAlignment: 72, urgencyMomentum: 68 },
  { label: "W6", intentTrend: 85, attentionDepth: 77, conversionReadiness: 74, trustAlignment: 76, urgencyMomentum: 72 },
];

export const ACTION_RECOMMENDATIONS: ActionRecommendation[] = [
  {
    id: "A-01",
    action: "Reassign broker",
    leadName: "Clara Bianchi",
    confidence: 87,
    impact: "+11% close probability",
    eta: "Today",
  },
  {
    id: "A-02",
    action: "Trigger concierge outreach",
    leadName: "Noura Al Mazrouei",
    confidence: 92,
    impact: "+17% trust alignment",
    eta: "Within 2h",
  },
  {
    id: "A-03",
    action: "Deploy founder content",
    leadName: "Sofia Von Heller",
    confidence: 84,
    impact: "+8 prestige resonance",
    eta: "Today",
  },
  {
    id: "A-04",
    action: "Schedule appointment",
    leadName: "Hamad Al Qasimi",
    confidence: 89,
    impact: "+14% conversion readiness",
    eta: "Next 24h",
  },
  {
    id: "A-05",
    action: "Increase luxury trust touchpoints",
    leadName: "Arjun Malhotra",
    confidence: 79,
    impact: "+9% intent trend",
    eta: "3 days",
  },
];
