import type {
  EvidenceItem,
  ExecutiveSignal,
  ForecastPoint,
  ReportCard,
  ReportCategory,
  ReportKpi,
  TimelineEvent,
} from "@/components/command-center/reports/types";

export const REPORT_CATEGORIES: ReportCategory[] = [
  "Luxury Market Intelligence Reports",
  "Founder Authority Reports",
  "Influence Intelligence Reports",
  "Lead Conversion Intelligence Reports",
  "Competitor Intelligence Reports",
  "Prestige Risk Reports",
  "Narrative Intelligence Reports",
  "Executive Strategy Briefings",
];

export const REPORT_KPIS: ReportKpi[] = [
  {
    id: "k1",
    label: "Executive Signal Strength",
    value: "92.1",
    deltaPct: 3.4,
    confidence: 91,
    momentum: "accelerating",
    commentary: "Cross-domain intelligence alignment increased decision clarity this cycle.",
    sparkline: [
      { x: "1", y: 58 },
      { x: "2", y: 64 },
      { x: "3", y: 69 },
      { x: "4", y: 75 },
      { x: "5", y: 82 },
      { x: "6", y: 89 },
    ],
  },
  {
    id: "k2",
    label: "Strategic Confidence Index",
    value: "88.7",
    deltaPct: 2.8,
    confidence: 89,
    momentum: "stable",
    commentary: "Confidence remains high across market, founder, and influence intelligence layers.",
    sparkline: [
      { x: "1", y: 56 },
      { x: "2", y: 60 },
      { x: "3", y: 65 },
      { x: "4", y: 70 },
      { x: "5", y: 76 },
      { x: "6", y: 82 },
    ],
  },
  {
    id: "k3",
    label: "Prestige Stability",
    value: "84.4",
    deltaPct: -1.1,
    confidence: 83,
    momentum: "cooling",
    commentary: "Prestige variance widened in one district and requires narrative reinforcement.",
    sparkline: [
      { x: "1", y: 73 },
      { x: "2", y: 74 },
      { x: "3", y: 75 },
      { x: "4", y: 74 },
      { x: "5", y: 72 },
      { x: "6", y: 70 },
    ],
  },
  {
    id: "k4",
    label: "Market Dominance Score",
    value: "79.9",
    deltaPct: 4.1,
    confidence: 87,
    momentum: "accelerating",
    commentary: "Dominance rose as competitor messaging fragmented across premium cohorts.",
    sparkline: [
      { x: "1", y: 48 },
      { x: "2", y: 53 },
      { x: "3", y: 59 },
      { x: "4", y: 65 },
      { x: "5", y: 72 },
      { x: "6", y: 79 },
    ],
  },
  {
    id: "k5",
    label: "Intelligence Velocity",
    value: "+18.6%",
    deltaPct: 5.2,
    confidence: 90,
    momentum: "accelerating",
    commentary: "AI report generation cadence is capturing shifts earlier in decision windows.",
    sparkline: [
      { x: "1", y: 41 },
      { x: "2", y: 47 },
      { x: "3", y: 54 },
      { x: "4", y: 61 },
      { x: "5", y: 69 },
      { x: "6", y: 76 },
    ],
  },
  {
    id: "k6",
    label: "Decision Impact Yield",
    value: "7.8x",
    deltaPct: 3.7,
    confidence: 88,
    momentum: "stable",
    commentary: "Board-level decisions linked to reports continue to outperform baseline outcomes.",
    sparkline: [
      { x: "1", y: 45 },
      { x: "2", y: 50 },
      { x: "3", y: 56 },
      { x: "4", y: 62 },
      { x: "5", y: 68 },
      { x: "6", y: 74 },
    ],
  },
];

export const REPORT_FEED: ReportCard[] = [
  {
    id: "r1",
    title: "Dubai Luxury Market Dominance Brief",
    category: "Luxury Market Intelligence Reports",
    confidence: 93,
    executiveImpact: "critical",
    summary: "Demand concentration and prestige momentum indicate a short window to consolidate premium market share.",
    risk: "medium",
    suggestedActions: ["Shift luxury positioning", "Expand HNWI penetration"],
    generatedAt: "6m ago",
    decisionPriority: "Immediate",
    executiveAudience: "C-Suite",
  },
  {
    id: "r2",
    title: "Founder Authority Reinforcement Report",
    category: "Founder Authority Reports",
    confidence: 90,
    executiveImpact: "high",
    summary: "Founder narrative resonance is rising, but trust reinforcement cadence is lagging in key investor channels.",
    risk: "low",
    suggestedActions: ["Increase founder narrative deployment", "Accelerate investor-facing messaging"],
    generatedAt: "18m ago",
    decisionPriority: "This Week",
    executiveAudience: "Founder Office",
  },
  {
    id: "r3",
    title: "Influence Cluster Conversion Intelligence",
    category: "Influence Intelligence Reports",
    confidence: 88,
    executiveImpact: "high",
    summary: "High-trust creator clusters are outperforming broad-reach campaigns in conversion gravity and wealth density.",
    risk: "medium",
    suggestedActions: ["Activate creator clusters", "Reduce prestige volatility"],
    generatedAt: "31m ago",
    decisionPriority: "This Week",
    executiveAudience: "Strategy Pod",
  },
  {
    id: "r4",
    title: "Prestige Volatility Exposure Report",
    category: "Prestige Risk Reports",
    confidence: 85,
    executiveImpact: "critical",
    summary: "Two narrative vectors show elevated prestige instability under competitor pressure.",
    risk: "high",
    suggestedActions: ["Increase trust reinforcement", "Increase exclusivity framing"],
    generatedAt: "47m ago",
    decisionPriority: "Immediate",
    executiveAudience: "Board",
  },
];

export const FORECAST_SERIES: ForecastPoint[] = [
  { label: "W1", baseline: 58, projected: 63, riskLower: 54, riskUpper: 68 },
  { label: "W2", baseline: 61, projected: 67, riskLower: 56, riskUpper: 72 },
  { label: "W3", baseline: 65, projected: 72, riskLower: 60, riskUpper: 76 },
  { label: "W4", baseline: 69, projected: 76, riskLower: 63, riskUpper: 81 },
  { label: "W5", baseline: 73, projected: 81, riskLower: 67, riskUpper: 86 },
  { label: "W6", baseline: 78, projected: 86, riskLower: 71, riskUpper: 91 },
];

export const EVIDENCE: EvidenceItem[] = [
  { id: "e1", source: "Market telemetry cluster", detail: "Premium inquiry depth rose 14% in DIFC and Palm segments.", confidence: 91 },
  { id: "e2", source: "Founder perception index", detail: "Executive trust sentiment improved after governance messaging.", confidence: 88 },
  { id: "e3", source: "Influence conversion model", detail: "High-trust creator cohorts generated 1.9x appointment quality.", confidence: 86 },
  { id: "e4", source: "Competitor narrative scan", detail: "Competitor positioning split across channels, reducing coherence.", confidence: 83 },
];

export const TIMELINE: TimelineEvent[] = [
  { id: "t1", label: "Major market shift", type: "market", severity: "high", timestamp: "09:10", note: "Premium demand migrated toward founder-led districts." },
  { id: "t2", label: "Founder sentiment change", type: "founder", severity: "medium", timestamp: "10:25", note: "Trust tone increased after investor roundtable release." },
  { id: "t3", label: "Influence volatility", type: "influence", severity: "medium", timestamp: "11:05", note: "One creator cluster showed sentiment spread widening." },
  { id: "t4", label: "Competitor positioning", type: "competitor", severity: "high", timestamp: "12:15", note: "Competitor launched rapid response prestige narrative." },
  { id: "t5", label: "Luxury audience movement", type: "audience", severity: "low", timestamp: "13:40", note: "HNWI overlap increased in finance-heavy channels." },
  { id: "t6", label: "Strategic inflection", type: "inflection", severity: "high", timestamp: "14:20", note: "AI suggests immediate exclusivity framing shift." },
];

export const EXEC_SIGNALS: ExecutiveSignal[] = [
  { id: "s1", type: "risk", title: "Strategic risk", body: "Prestige confidence dipped below threshold in one report stream.", timestamp: "3m ago" },
  { id: "s2", type: "anomaly", title: "AI anomaly", body: "Narrative penetration decoupled from trust transfer in one cohort.", timestamp: "8m ago" },
  { id: "s3", type: "prestige", title: "Prestige instability", body: "Volatility spike detected after competitor founder interview.", timestamp: "13m ago" },
  { id: "s4", type: "competitor", title: "Competitor acceleration", body: "Competitor strategy briefing cadence increased 2x this week.", timestamp: "19m ago" },
  { id: "s5", type: "narrative", title: "Narrative disruption", body: "Founder theme overlap suggests dilution risk in premium channels.", timestamp: "27m ago" },
  { id: "s6", type: "volatility", title: "Market volatility warning", body: "Luxury audience movement variance elevated in 48h window.", timestamp: "34m ago" },
];
